version: 2

models:
    - name: fact_orders
      description: "Nossa tabela de fatos"
      columns:
          - name: order_id
            description: "Chave primária original da tabela"
            tests:
                - not_null

    - name: dim_customers
      description: "Dimensão de clientes"
      columns:
          - name: customer_id
            description: "Id do cliente"
            tests:
                - unique
                - not_null

    - name: dim_shippers
      description: "Dimensão de entregadores"
      columns:
          - name: shipper_id
            description: "Id do entregador"
            tests:
                - unique
                - not_null

    - name: dim_employees
      description: "Dimensão de empregados"
      columns:
          - name: employee_id
            description: "Id do empregado"
            tests:
                - unique
                - not_null
    
    - name: dim_products
      description: "Dimensão de produtos"
      columns:
          - name: product_id
            description: "Id do produto"
            tests:
                - unique
                - not_null
